# Use postgres/example user/password credentials
version: '3.9'

services:
  # python-client-react-vite:
  #   image: python-client-react-vite
  #   depends_on:
  #     - api-todo
  #   build:
  #     context: ./frontEnd/
  #     dockerfile: Dockerfile.1
  #   init: true
  #   volumes:
  #     - type: bind
  #       source: ./frontEnd/
  #       target: /usr/src/app/
  #     - type: volume
  #       target: /usr/src/app/node_modules 
  #     - type: bind
  #       source: ./frontEnd/vite.config.ts
  #       target: /usr/src/app/vite.config.ts
  #   networks:
  #     - frontend
  #   ports:
  #     - 5173:5173
  # python-client-react-nginx:
  #   image: python-client-react-nginx
  #   depends_on:
  #     - api-todo
  #   build:
  #     context: ./frontEnd/
  #     dockerfile: Dockerfile
  #   init: true
  #   networks:
  #     - frontend
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped

  # api-todo:
  #   build: 
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000

  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - pg-db
  #   networks:
  #     - backend
  #     - frontend

  pg-db:
    image: postgres
    networks:
      - backend
    volumes:
      - "postgres:/data/postgres"
    env_file:
      - .env
    ports:
      - 5433:5432

  adminer:
    image: adminer
    networks:
      - backend
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - pg-db
volumes:
  postgres:

networks:
  frontend:
  backend:
