# Generated by Django 5.1.4 on 2024-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_email',
            field=models.CharField(default='sample_email@gmail.com', max_length=120),
        ),
    ]
